// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-0rPpqTosxN-4EruvaVGjerWi4lym7w',
    appId: '1:477721594915:web:dae47211e41f2517a27596',
    messagingSenderId: '477721594915',
    projectId: 'qosambs-fd8aa',
    authDomain: 'qosambs-fd8aa.firebaseapp.com',
    storageBucket: 'qosambs-fd8aa.appspot.com',
    measurementId: 'G-TYM5PPYEL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmM3cVnWk0hywdCgyxLazOZHHpjuqZPTI',
    appId: '1:477721594915:android:c32b77d9e32a0f9aa27596',
    messagingSenderId: '477721594915',
    projectId: 'qosambs-fd8aa',
    storageBucket: 'qosambs-fd8aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzrU69ihWuedj-0lExhSQOZ9g0NG1lJRU',
    appId: '1:477721594915:ios:b929791cecaca894a27596',
    messagingSenderId: '477721594915',
    projectId: 'qosambs-fd8aa',
    storageBucket: 'qosambs-fd8aa.appspot.com',
    iosBundleId: 'com.example.qosambassadors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzrU69ihWuedj-0lExhSQOZ9g0NG1lJRU',
    appId: '1:477721594915:ios:b929791cecaca894a27596',
    messagingSenderId: '477721594915',
    projectId: 'qosambs-fd8aa',
    storageBucket: 'qosambs-fd8aa.appspot.com',
    iosBundleId: 'com.example.qosambassadors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-0rPpqTosxN-4EruvaVGjerWi4lym7w',
    appId: '1:477721594915:web:f571c9c39b22af10a27596',
    messagingSenderId: '477721594915',
    projectId: 'qosambs-fd8aa',
    authDomain: 'qosambs-fd8aa.firebaseapp.com',
    storageBucket: 'qosambs-fd8aa.appspot.com',
    measurementId: 'G-STGL9ETT64',
  );
}
